### ISSUE TITLE
error foodle

### ISSUE THREAD

**Issue by farrahe** [UNINETT/Foodle#25]
Hello,

Simplesaml is ok, i have test it, but foodle cause a error
you have any idee

/var/www/foodle/config/config.php: Could not retrieve the required option 'entityid'
#0 /var/www/simplesamlphp/lib/SimpleSAML/Configuration.php(534): SimpleSAML_Configuration->getValue('entityid', '___REQUIRED_OPT...')
#1 /var/www/foodle/lib/FoodleAuth.php(34): SimpleSAML_Configuration->getString('entityid')
#2 /var/www/foodle/www/index.php(309): FoodleAuth->__construct(Object(FoodleDBConnector))

**Comment by MvdB** [comment]
Hi Guys,

we got the same issue here. Are there any advice by now?

Thank you in advance

**Comment by serversplit** [comment]
I have the same problem here. Tried the installation using the distribution package and with the versions of the foodle installation documentation and got the same error

**Comment by precurse** [comment]
Did you guys find the solution?

You can follow the patches that I used to get it working for us..  https://github.com/cybera/Foodle  

This particular patch fixed this error though:  https://github.com/cybera/Foodle/commit/3c62d94f8812ba3e02bc1b05b0083030a1a910bd
